In [3]:
import pandas as pd

In [4]:
dept = pd.read_csv(r"E:\2026\PROJECCTS\Instakart_REtail_project\departments.csv")

In [5]:
prior_order_prod = pd.read_csv(r"E:\2026\PROJECCTS\Instakart_REtail_project\order_products__prior.csv")

In [6]:
orders= pd.read_csv(r"E:\2026\PROJECCTS\Instakart_REtail_project\orders.csv")

In [7]:
prod = pd.read_csv(r"E:\2026\PROJECCTS\Instakart_REtail_project\products.csv")

In [8]:
print(f" columns of department {dept.columns}")
print(f"coulmns of order_products_prior table {prior_order_prod.columns}")
print(f"columns of orders table {orders.columns}")
print(f"columns of products table {prod.columns}")

 columns of department Index(['department_id', 'department'], dtype='object')
coulmns of order_products_prior table Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='object')
columns of orders table Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')
columns of products table Index(['product_id', 'product_name', 'aisle_id', 'department_id'], dtype='object')

In [9]:
first_half_merge = pd.merge(prod,dept, on="department_id", how = "left")
first_half_merge

,product_id,product_name,aisle_id,department_id,department
0,1,Chocolate Sandwich Cookies,61,19,snacks
1,2,All-Seasons Salt,104,13,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,frozen
4,5,Green Chile Anytime Sauce,5,13,pantry
...,...,...,...,...,...
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,alcohol
49684,49685,En Croute Roast Hazelnut Cranberry,42,1,frozen
49685,49686,Artisan Baguette,112,3,bakery
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,pets
49687,49688,Fresh Foaming Cleanser,73,11,personal care

In [10]:
half_merged =  pd.merge(orders, prior_order_prod, on="order_id")
half_merged

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,2539329,1,prior,1,2,8,NaN,196,1,0
1,2539329,1,prior,1,2,8,NaN,14084,2,0
2,2539329,1,prior,1,2,8,NaN,12427,3,0
3,2539329,1,prior,1,2,8,NaN,26088,4,0
4,2539329,1,prior,1,2,8,NaN,26405,5,0
...,...,...,...,...,...,...,...,...,...,...
32434484,2977660,206209,prior,13,1,12,7.0,14197,5,1
32434485,2977660,206209,prior,13,1,12,7.0,38730,6,0
32434486,2977660,206209,prior,13,1,12,7.0,31477,7,0
32434487,2977660,206209,prior,13,1,12,7.0,6567,8,0
32434488,2977660,206209,prior,13,1,12,7.0,22920,9,0

In [11]:
sales_lines_clean = pd.merge(half_merged, first_half_merge, on = "product_id")
sales_lines_clean.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,department
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,beverages
1,2539329,1,prior,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,dairy eggs
2,2539329,1,prior,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,snacks
3,2539329,1,prior,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,snacks
4,2539329,1,prior,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,household

In [12]:
sales_lines_clean = sales_lines_clean.drop(["eval_set","order_number","add_to_cart_order","reordered","aisle_id"],axis=1)
sales_lines_clean.head()

,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department_id,department
0,2539329,1,2,8,NaN,196,Soda,7,beverages
1,2539329,1,2,8,NaN,14084,Organic Unsweetened Vanilla Almond Milk,16,dairy eggs
2,2539329,1,2,8,NaN,12427,Original Beef Jerky,19,snacks
3,2539329,1,2,8,NaN,26088,Aged White Cheddar Popcorn,19,snacks
4,2539329,1,2,8,NaN,26405,XL Pick-A-Size Paper Towel Rolls,17,household

In [13]:
sales_lines_clean.shape

(32434489, 9)

In [14]:
sales_lines_clean["product_name"] = sales_lines_clean["product_name"].astype(str).str.strip().str.lower()
sales_lines_clean["department"]=sales_lines_clean["department"].astype(str).str.strip().str.lower()
sales_lines_clean.head()

,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department_id,department
0,2539329,1,2,8,NaN,196,soda,7,beverages
1,2539329,1,2,8,NaN,14084,organic unsweetened vanilla almond milk,16,dairy eggs
2,2539329,1,2,8,NaN,12427,original beef jerky,19,snacks
3,2539329,1,2,8,NaN,26088,aged white cheddar popcorn,19,snacks
4,2539329,1,2,8,NaN,26405,xl pick-a-size paper towel rolls,17,household

In [15]:
sales_lines_clean["days_since_prior_order"]=sales_lines_clean["days_since_prior_order"].fillna(0)
sales_lines_clean.head()

,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department_id,department
0,2539329,1,2,8,0.0,196,soda,7,beverages
1,2539329,1,2,8,0.0,14084,organic unsweetened vanilla almond milk,16,dairy eggs
2,2539329,1,2,8,0.0,12427,original beef jerky,19,snacks
3,2539329,1,2,8,0.0,26088,aged white cheddar popcorn,19,snacks
4,2539329,1,2,8,0.0,26405,xl pick-a-size paper towel rolls,17,household

In [16]:
sales_lines_clean[["order_id","user_id","order_dow","order_hour_of_day","days_since_prior_order","product_id","department_id"]]=sales_lines_clean.loc[0:][["order_id","user_id","order_dow","order_hour_of_day","days_since_prior_order","product_id","department_id"]].astype(int)

In [17]:
import random
product_price = {}
price = []
unique=sales_lines_clean.iloc[0:,6].unique()
for i in range(len(unique)):
    price.append(random.randint(1,15))
product_price = dict(zip(unique, price))
print(dict(list(product_price.items())[:7]))


#print(unique_values)

{'soda': 11, 'organic unsweetened vanilla almond milk': 14, 'original beef jerky': 13, 'aged white cheddar popcorn': 15, 'xl pick-a-size paper towel rolls': 12, 'pistachios': 6, 'bag of organic bananas': 3}

In [39]:
sales_lines_clean["price"] = sales_lines_clean["product_name"].map(product_price)
sales_lines_clean.head()

TypeError: unsupported operand type(s) for -: 'dict' and 'list'

In [19]:
import datetime 
#print(dir(datetime.datetime))
start_date = datetime.date(2025,1,6)
date =[]

for i in range (len(sales_lines_clean)):
    rangedate = datetime.timedelta(random.randint(0,41))
    date.append(start_date + rangedate)
sales_lines_clean["date"] = date

In [20]:
sales_lines_clean["date"] = pd.to_datetime(sales_lines_clean["date"])
diff = sales_lines_clean["date"] - pd.Timestamp(start_date)
diff=diff.dt.days
sales_lines_clean["week"] = (diff//7)+1
sales_lines_clean.head(10)

,order_id,user_id,order_dow,order_hour_of_day,days_since_prior_order,product_id,product_name,department_id,department,price,date,week
0,2539329,1,2,8,0,196,soda,7,beverages,11,2025-01-15,2
1,2539329,1,2,8,0,14084,organic unsweetened vanilla almond milk,16,dairy eggs,14,2025-01-29,4
2,2539329,1,2,8,0,12427,original beef jerky,19,snacks,13,2025-02-13,6
3,2539329,1,2,8,0,26088,aged white cheddar popcorn,19,snacks,15,2025-01-20,3
4,2539329,1,2,8,0,26405,xl pick-a-size paper towel rolls,17,household,12,2025-02-13,6
5,2398795,1,3,7,15,196,soda,7,beverages,11,2025-02-03,5
6,2398795,1,3,7,15,10258,pistachios,19,snacks,6,2025-01-18,2
7,2398795,1,3,7,15,12427,original beef jerky,19,snacks,13,2025-01-15,2
8,2398795,1,3,7,15,13176,bag of organic bananas,4,produce,3,2025-01-08,1
9,2398795,1,3,7,15,26088,aged white cheddar popcorn,19,snacks,15,2025-01-19,2

In [21]:
sales_lines_clean["date"].astype("datetime64[ns]")

0          2025-01-15
1          2025-01-29
2          2025-02-13
3          2025-01-20
4          2025-02-13
              ...
32434484   2025-01-24
32434485   2025-01-24
32434486   2025-01-29
32434487   2025-02-14
32434488   2025-02-07
Name: date, Length: 32434489, dtype: datetime64[ns]

In [22]:
sales_lines_clean["date"].max()

Timestamp('2025-02-16 00:00:00')

In [23]:
sales_lines_clean["date"].min()

Timestamp('2025-01-06 00:00:00')

In [24]:
sales_lines_clean=sales_lines_clean.sort_values(by=["product_id","date"], ascending= True)

In [25]:
sample_data = sales_lines_clean.sample(100000, random_state=25)

In [26]:
qty =[]
for i in range(len(sample_data)):
    qty.append(random.randint(1,6))
sample_data["qty"]=qty

In [27]:
sample_data["row_revenue"] = sample_data["price"] * sample_data["qty"]

In [28]:
day_number= sample_data["date"] - pd.Timestamp("2025-01-06")
day_number= day_number.dt.days
sample_data["day_number"]= day_number+1

In [29]:
sample_data=sample_data.sort_values(by=["date","product_id"],ascending=True)

In [30]:
#Top 10 products by quantity sold Include: product name, department, total qty, total revenue
sellers = sample_data.groupby(['week','product_name','department']).agg(total_qty=('qty','sum'), total_revenue=('row_revenue','sum'))
sellers= sellers.sort_values(by =['week','total_qty'], ascending=[True, False])
weekly_best_sellers=sellers.groupby('week').head(10)
weekly_best_sellers.to_csv("weekly_best_sellers.csv")

In [31]:
#Bottom 5 products by quantity sold Include: product name, department, total qty, total revenue
sellers = sample_data.groupby(['week','product_name','department']).agg(total_qty=('qty','sum'), total_revenue=('row_revenue','sum'))
sellers= sellers.sort_values(by=['week','total_qty'], ascending=[True,True])
weekly_worst_sellers = sellers.groupby('week').head(5)
weekly_worst_sellers.to_csv("weekly_worst_sellers.csv")

In [32]:
#otal sales per department Include: week,department, total qty, total revenue, number of different products sold

sales= sample_data.groupby(['week','department']).agg(total_qty=('qty','sum'), total_revenue=('row_revenue','sum'),num_products=("product_name","nunique"))
weekly_category_sales= sales
weekly_category_sales.to_csv("weekly_category_sales.csv")

In [38]:
sample_data = sample_data.to_csv("sample_data.csv")

In [33]:
summary1 = sample_data["order_id"].nunique()
summary2 = sample_data["row_revenue"].sum()
summary3 = summary2/summary1
summary4 = sample_data["product_name"].nunique()
summary5=sample_data.groupby('department').row_revenue.sum()
summary5 = summary5.sort_values(ascending=False)
summary5 = summary5[:3]
s5=summary5.index
summary_sales = pd.DataFrame([{"Total_transaction": summary1,"total_revenue":summary2, "Avg_order_value" :summary3, "num_uproducts":summary4, "top_dept_sales":[s5] }])
summary_sales.to_csv("summary_sales.csv")